### PR TITLE
Update wiremapper runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- runtime: Update runtime to 46
- appdata: Fix missing developer name

### CODE REVIEW

**Comment by ghost** [comment]
@MartijnBraam I've updated the wiremapper runtime to version 46 since runtime version 42 has reached end-of-life.

I don't have a Pockethernet. Could you test this PR.

**Comment by ghost** [comment]
@barthalion  I've updated the wiremapper runtime to version 46 but I don't have a Pockethernet to test the application.

**Comment by bbhtt** [comment]
bot, build

**Comment by ghost** [comment]
Patches sent to upstream. https://gitlab.com/MartijnBraam/wiremapper/-/merge_requests/2

**Pull request merged**
